
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myjournalapp
  password: <%= ENV['MY_JOURNAL_APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: my_journal_app_development

test:
  <<: *default
  database: my_journal_app_test

production:
  <<: *default
  database: my_journal_app_production
